// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const FORBIDDEN_HEADERS = new Set(['x-project-code']);

const stripForbiddenHeaders = (headers: Headers): Headers => {
  const cleanedHeaders = new Headers();

  headers.forEach((value, key) => {
    if (!FORBIDDEN_HEADERS.has(key.toLowerCase())) {
      cleanedHeaders.set(key, value);
    }
  });

  return cleanedHeaders;
};

const buildSanitizedHeaders = (headers?: HeadersInit): Headers | undefined => {
  if (!headers) return undefined;
  return stripForbiddenHeaders(new Headers(headers));
};


const sanitizeLaunchPhasesUrl = (url: string): string => {
  try {
    const parsedUrl = new URL(url);
    const isLaunchPhasesEndpoint = parsedUrl.pathname.endsWith('/rest/v1/launch_phases');

    if (!isLaunchPhasesEndpoint) return url;

    if (parsedUrl.searchParams.has('funnel_id')) {
      parsedUrl.searchParams.delete('funnel_id');
    }

    return parsedUrl.toString();
  } catch {
    return url;
  }
};

const sanitizedSupabaseFetch: typeof fetch = (input, init) => {
  if (input instanceof Request) {
    const requestHeaders = stripForbiddenHeaders(input.headers);
    const sanitizedUrl = sanitizeLaunchPhasesUrl(input.url);

    const request = new Request(sanitizedUrl, {
      method: input.method,
      headers: buildSanitizedHeaders(init?.headers) ?? requestHeaders,
      body: init?.body ?? input.body,
      mode: input.mode,
      credentials: input.credentials,
      cache: input.cache,
      redirect: input.redirect,
      referrer: input.referrer,
      referrerPolicy: input.referrerPolicy,
      integrity: input.integrity,
      keepalive: input.keepalive,
      signal: init?.signal ?? input.signal,
    });

    return fetch(request);
  }

  const sanitizedInput = typeof input === 'string' ? sanitizeLaunchPhasesUrl(input) : input;

  return fetch(sanitizedInput, {
    ...init,
    headers: buildSanitizedHeaders(init?.headers),
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: sanitizedSupabaseFetch,
    headers: {
      apikey: SUPABASE_PUBLISHABLE_KEY,
      'x-client-info': 'supabase-js-web',
    },
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public',
  },
});
